Dev-FE-1/ToyProject_3_Team2

src/components/buttons/Button.tsx

closes #11 
각 사이즈별 small과 large로 나뉨
- large 버튼은 width가 100%, height가 50px로 설정됨
- small 버튼은 width가 없고, height가 32px로 설정됨
- 탐색 페이지의 카테고리 Toggle 버튼 ( `전체`, `스포츠`, `음악`..)
- 새 재생목록 생성 시 `파일추가` 버튼
```tsx
// import 해와야 하는 것들
import { css } from '@emotion/react';
import Button from '@/components/buttons/Button';
import theme from '@/styles/theme';
// 어떻게 사용하는지
// styleType 속성값에 따라 글자색/배경색 변경
<Button>첫째 버튼</Button>
<Button styleType='secondary'>둘째 버튼</Button>
<Button styleType='tertiary'>셋째 버튼</Button>
<Button styleType='ghost'>고스트 버튼</Button>
<Button styleType='disabled'>비활성화 버튼</Button>
// 사이즈가 없는 버튼으로 높이만 추가 설정가능 => 
// customeStyle 속성을 통해 스타일 추가
// emotion의 css 사용: 형식은 코드 참고
<Button styleType='textBlue' customStyle={css({ height: 'auto' })}>
나는 사이즈가 없는 버튼
</Button>
<Button …
```

[Feat] 버튼 컴포넌트 생성

---

package-lock.json

브레이스 잘 열고 닫읍시다
package-lock.json 만 변경되었음 (npm install 안하셔도 되요)

Fix/package lock 수정

---

src/components/page/comment/CommentBox.tsx
src/components/page/playlistdetail/VideoBoxDetail.tsx
src/components/page/videoModal/VideoModal.tsx
src/hooks/mutations/usePlaylistMutations.ts
src/hooks/usePlaylistData.ts
src/pages/PlaylistPage.tsx

mutation 함수명 변경
- 함수명에 mutation이라는 단어가 들어가면 너무 길어질 것 같아서 mutation을 제거
VideoModal에서 각 동영상 삭제 기능 추가
- VideoModal에서 각 동영상 삭제 기능 추가
- 동영상 삭제 시 해당 동영상이 곧바로 삭제되며 리렌더링: 남은 동영상만 보여짐
- 동영상 삭제 성공 시 토스트 메시지로 삭제 성공 알림
- 동영상 삭제 시 해당 동영상이 재생 중이었다면 다음 동영상으로 자동 재생
비디오 모달에서 영상 순서변경하면 상위에 보이는 영상 순서도 변경
- 드래그앤드롭으로 영상 순서 변경 시, 변경된 순서대로 인덱스값이 변경되어 보여짐

[Feat] 비디오모달에서 동영상 삭제 기능 추가 및 업데이트된 동영상 순서대로 인덱스 보여지는 기능 추가

---

src/components/common/Badge.tsx
src/components/common/ThumbNailBox.tsx
src/components/page/home/RecentUpdateList.tsx

[design] 디자인 수정

---

src/components/common/PlaylistItem.tsx
src/components/common/ToggleSwitch.tsx
src/components/page/home/RecentUpdateList.tsx

[fix] 홈페이지 최신 플리에서 1~5번 데이터만 뜨는 버그 해결

---

src/components/page/home/DetailList.tsx
src/hooks/useSortedPlaylists.ts
src/router/Router.tsx

- 인기 플레이리스트 좋아요 0인 플레이리스트는 보이지 않게 수정

[Fix] 인기 플레이리스트 좋아요 0인 플레이리스트는 보이지 않게 수정

---

src/pages/CommentList.tsx

첫 필터링 이후 필터링이 제대로 되지 않는 현상을 수정하였습니다.
https://github.com/user-attachments/assets/c9e4a46d-4ebd-4652-94c2-565ad4e24a3f

[Fix] 댓글 필터링 오류 수정

---

src/components/page/videoModal/VideoModal.tsx
src/hooks/mutations/usePlaylistMutations.ts
src/hooks/usePlaylistData.ts

fix: 비디오 모달에서 비디오 삭제 시 바로 삭제되고 재 랜더링 되는 기능

---

src/components/page/videoModal/VideoModal.tsx

[Fix] 비디오 모달에서 비디오 영상 순서 변경 시 변경된 인덱스로 상위에 보여지도록 수정

---

src/pages/Settings.tsx
src/pages/Signin.tsx
src/router/Router.tsx

로그인페이지 엔터키 적용 및 로그인 로그아웃 auth 인증 사용

[fix] 로그인페이지 엔터키 적용 및 로그인 로그아웃 auth 인증 사용

---

src/pages/Mypage.tsx
src/pages/PlaylistEdit.tsx
src/pages/PlaylistPage.tsx
src/router/Router.tsx

close #185
로그인이 되지 않았을때 유효하지 않은 주소를 입력하면 로그인페이지로 이동
로그인이 되어있을때 유효하지 않은 주소를 입력하면 404페이지로 이동

[fix] 로그인여부에 따라 로그인페이지로 이동 및 404페이지 이동

---

src/hooks/usePlaylistForm.ts

close #196 
플레이리스트 수정시 기존 썸네일 로드 안되는 현상 수정

[fix] 플레이리스트 수정시 기존 썸네일 이미지 안나오는 현상

---

src/hooks/queries/usePlaylistQueries.ts
src/hooks/queries/useUserQueries.ts
src/hooks/useFilteredPlaylists.ts

- TanStack Query stale time 2000ms로 수정
- 기존 5분의 경우, 데이터 업데이트가 느리다고 판단

[Fix] TanStack Query stale time 2000ms로 수정

---

README.md

docs: 리드미 대문이미지 추가

---

README.md

docs: 리드미 사용자페이지 이미지 업로드

---

src/constants/playlist.ts
src/pages/Onboarding.tsx
src/pages/Subscriptions.tsx

closes #201 
구독한 목록이 없을때 표시하는 데이터

[feat] 구독 페이지 없을 때 표시

---

README.md

[docs] Update README (#189)

---

src/components/page/mypage/FlipCard.tsx
src/components/page/mypage/MyProfile.tsx
src/components/page/playlist/PlaylistBox.tsx
src/components/page/playlistdetail/ThumbNailBoxDetail.tsx
src/components/page/playlistdetail/VideoBoxDetail.tsx
src/components/page/profile/Profile.tsx
src/pages/Subscriptions.tsx
src/utils/string.ts

design: 전체 스타일수정

---

src/tests/PlaylistCreate.test.ts

closes #209 
playwright로 로그인 후 플레이리스트를 추가하는 로직 테스트코드를 작성하였습니다

[feat] 로그인 후 플리 추가하는 테스트코드 작성

---

README.md

[docs] README 파일구조 추가
